version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - ../.development.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@mail.ru'
      PGADMIN_DEFAULT_PASSWORD: 'root'
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  pgdata:
